[package]
name = "lox-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyline = "15.0.0"
snafu = "0.8.5"
macros = { path = "./macros/" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
ordered-float = "4.6.0"

